services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code
    working_dir: /code
    command: uvicorn app:app --host 0.0.0.0 --port 8000