name: remove-bg-ci
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy files
        uses: actions/checkout@v3
        
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: make test
        run: pytest . -x -s --cov=code -vv